---
title: "IS605-Assignment-12"
author: "J. Hamski"
date: "November 14, 2015"
output: html_document
---

##IS605 -- ASSIGNMENT 12 -- BIAS VARIANCE TRADEOFF IN R

```{r, message=FALSE, warning=FALSE}
require(stats)
require(boot)
require(readr)
```


```{r}
col.names = c("displacement", "horsepower", "weight", "acceleration", "mpg")
cars <- read_csv(file="auto-mpg.csv", col_names=col.names)
```

```{r}
glm.fit.1 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,1), data=cars)
glm.fit.2 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,2), data=cars)
glm.fit.3 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,3), data=cars)
glm.fit.4 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,4), data=cars)
glm.fit.5 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,5), data=cars)
glm.fit.6 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,6), data=cars)
glm.fit.7 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,7), data=cars)
glm.fit.8 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,8), data=cars)
glm.fit.9 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,9), data=cars)
glm.fit.10 <- glm(mpg~poly(displacement+horsepower+weight+acceleration,10), data=cars)
```


```{r}
set.seed(284)
cv.err.1 <- cv.glm(cars,glm.fit.1,K=5)$delta[1]
cv.err.2 <- cv.glm(cars,glm.fit.2,K=5)$delta[1]
cv.err.3 <- cv.glm(cars,glm.fit.3,K=5)$delta[1]
cv.err.4 <- cv.glm(cars,glm.fit.4,K=5)$delta[1]
cv.err.5 <- cv.glm(cars,glm.fit.5,K=5)$delta[1]
cv.err.6 <- cv.glm(cars,glm.fit.6,K=5)$delta[1]
cv.err.7 <- cv.glm(cars,glm.fit.7,K=5)$delta[1]
cv.err.8 <- cv.glm(cars,glm.fit.8,K=5)$delta[1]
cv.err.9 <- cv.glm(cars,glm.fit.9,K=5)$delta[1]
cv.err.10 <- cv.glm(cars,glm.fit.10,K=5)$delta[1]


cv.err <- rbind(cv.err.1, cv.err.2,cv.err.3,cv.err.4,cv.err.5,cv.err.6,cv.err.7,cv.err.8, cv.err.9, cv.err.10)
```

```{r}
plot(x = 1:10, cv.err, type='b')
```



```{r}
poly.fit <-function(degree){
  glm.fit <- glm(mpg~poly(displacement+horsepower+weight+acceleration,degree), data=cars)
  return(glm.fit)}

max.degree = 8

glm.fit.all <- sapply(1:max.degree, FUN=poly.fit)
```


```{r}
cross.validate <- function(models){
  print(models)
  cv.err <- cv.glm(cars, models, K=5)$delta
  #print(cv.err)
  }
```

